# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: emerald

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'The highly-customizable Hugo Academic theme powered by Hugo Blox Builder. Easily create your personal academic website.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Home Page"

# Site footer
footer:
  copyright:
    notice: '© {year} Ye Jia. All rights reserved.'
    license:
      enable: false
      allow_derivatives: false
      share_alike: false
      allow_commercial: false
  show_powered_by: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
  comments:
    enable: true
    provider: giscus
    giscus:
      repo: "Ye-0413/Ye-0413.github.io"  # Your GitHub repository
      repo_id: ""  # We'll need to get this
      category: "Comments"  # The category for discussions
      mapping: "pathname"  # How to map discussions to pages
